language: node_js
node_js: 
    - 10

cache: 
    yarn: true
    directories:
        - node_modules

stages:
    - test

install:
    - yarn global add codecov

before-script:
    - yarn ci

env:
    - PRIVATE_KEY=$PRIVATE_KEY
    - DB_URL=$DB_URL
    - DB_URL_TEST=$DB_URL_TEST
    - SMTP_HOST=$SMTP_HOST
    - SMTP_PORT=$SMTP_PORT
    - SMTP_USER=$SMTP_USER
    - SMTP_PASS=$SMTP_PASS

jobs: 
    include: 
        - stage: test
            name: 'Unit Testing'
            script: 
                - yarn test-cov